name = "rtr-site"
compatibility_date = "2024-08-26"

account_id = "54d2bb9a046e4bf7bf02628a8493eb8e"
workers_dev = true

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "rtr-presskit"
preview_bucket_name = "rtr-presskit" 